create table public.roles (
  id bigint generated by default as identity not null,
  nombre text not null,
  descripcion text null,
  disponible_en_registro boolean not null default false,
  constraint roles_pkey primary key (id)
) TABLESPACE pg_default;